# Generated by Django 3.2.12 on 2022-03-30 08:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220328_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
